name: irtzalink_mobile
description: Mobile app for IrtzaLink with animations, Firebase + Supabase integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.1
  # Supabase
  supabase_flutter: ^2.5.8
  # UI/UX
  animations: ^2.0.11
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  mobile_scanner: ^5.2.1
  image_picker: ^1.1.2
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
