name: irtzalink
description: Personal link management system - Flutter app for IrtzaLink

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (Latest stable versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  
  # Authentication (Enhanced)
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  
  # Backend Integration
  supabase_flutter: ^2.0.0
  
  # Navigation & State Management (Enhanced)
  go_router: ^12.0.0
  provider: ^6.1.1
  riverpod: ^2.4.0
  
  # Animations & UI (New)
  rive: ^0.12.0
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  
  # UI and Navigation (Enhanced)
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  
  # Sharing and URL launching
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  
  # Storage and persistence
  shared_preferences: ^2.2.2
  
  # HTTP requests
  http: ^1.1.2
  
  # Utils
  uuid: ^3.0.7
  intl: ^0.18.1
  
  # Icons
  font_awesome_flutter: 10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Testing
  integration_test:
    sdk: flutter
  mockito: ^5.4.2

# flutter_launcher_icons:
#   android: true
#   ios: false
#   image_path: "assets/icons/app_icon.png"
#   adaptive_icon_background: "#1E1E2E"
#   adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
#   min_sdk_android: 21
#   web:
#     generate: false
#   windows:
#     generate: false
#   macos:
#     generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    
