name: Build Flutter APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true
        
    - name: Create google-services.json with real Firebase config
      run: |
        mkdir -p flutter_app/android/app
        echo "ewogICJwcm9qZWN0X2luZm8iOiB7CiAgICAicHJvamVjdF9udW1iZXIiOiAiMzQyOTg0Njg1MTMzIiwKICAgICJwcm9qZWN0X2lkIjogImlydHphbGluay00ZDQwNyIsCiAgICAic3RvcmFnZV9idWNrZXQiOiAiaXJ0emFsaW5rLTRkNDA3LmZpcmViYXNlc3RvcmFnZS5hcHAiCiAgfSwKICAiY2xpZW50IjogWwogICAgewogICAgICAiY2xpZW50X2luZm8iOiB7CiAgICAgICAgIm1vYmlsZXNka19hcHBfaWQiOiAiMTozNDI5ODQ2ODUxMzM6YW5kcm9pZDphYjczNWNlYjZjM2Y0MjVmZjM4ZTA0IiwKICAgICAgICAiYW5kcm9pZF9jbGllbnRfaW5mbyI6IHsKICAgICAgICAgICJwYWNrYWdlX25hbWUiOiAiY29tLmlydHphbGluay5hcHAiCiAgICAgICAgfQogICAgICB9LAogICAgICAib2F1dGhfY2xpZW50IjogWwogICAgICAgIHsKICAgICAgICAgICJjbGllbnRfaWQiOiAiMzQyOTg0Njg1MTMzLWRobnRpZ29ibWVwMnJmbTMyMzVxamNyMWNiMWlqZmwxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwKICAgICAgICAgICJjbGllbnRfdHlwZSI6IDMKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJhcGlfa2V5IjogWwogICAgICAgIHsKICAgICAgICAgICJjdXJyZW50X2tleSI6ICJBSXphU3lCMGJkVWpVQS1pQkVrNnd1YlJxVWtBQXFqdTNCQWlaR3ciCiAgICAgICAgfQogICAgICBdLAogICAgICAic2VydmljZXMiOiB7CiAgICAgICAgImFwcGludml0ZV9zZXJ2aWNlIjogewogICAgICAgICAgIm90aGVyX3BsYXRmb3JtX29hdXRoX2NsaWVudCI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICJjbGllbnRfaWQiOiAiMzQyOTg0Njg1MTMzLWRobnRpZ29ibWVwMnJmbTMyMzVxamNyMWNiMWlqZmwxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwKICAgICAgICAgICAgICAiY2xpZW50X3R5cGUiOiAzCiAgICAgICAgICAgIH0KICAgICAgICAgIF0KICAgICAgICB9CiAgICAgIH0KICAgIH0KICBdLAogICJjb25maWd1cmF0aW9uX3ZlcnNpb24iOiAiMSIKfQ==" | base64 -d > flutter_app/android/app/google-services.json

    - name: Clear pub cache and get dependencies
      working-directory: flutter_app
      run: |
        flutter pub cache clean
        flutter pub get
      
    - name: Build APK (release)
      working-directory: flutter_app
      run: flutter build apk --release

    - name: Build AAB (release for Play)
      working-directory: flutter_app
      run: flutter build appbundle --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: IrtzaLink-APK
        path: flutter_app/build/app/outputs/flutter-apk/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: IrtzaLink-AAB
        path: flutter_app/build/app/outputs/bundle/release/app-release.aab

    - name: Create Release Notes
      run: |
        echo "## IrtzaLink Mobile App Release" > release_notes.md
        echo "" >> release_notes.md
        echo "### Features:" >> release_notes.md
        echo "- 📱 Complete profile management" >> release_notes.md
        echo "- 🔗 Social media links management" >> release_notes.md
        echo "- 📊 Analytics and statistics" >> release_notes.md
        echo "- 📱 QR code generation and scanning" >> release_notes.md
        echo "- 🎨 Professional UI/UX" >> release_notes.md
        echo "- 🔄 Real-time sync with Firebase" >> release_notes.md
