name: Build Flutter APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Create dummy google-services.json for build
      run: |
        mkdir -p flutter_app/android/app
        echo '{
          "project_info": {
            "project_number": "123456789",
            "project_id": "irtzalink-demo",
            "storage_bucket": "irtzalink-demo.appspot.com"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:123456789:android:abcd1234",
                "android_client_info": {
                  "package_name": "com.irtzalink.app"
                }
              },
              "oauth_client": [
                {
                  "client_id": "123456789-abcd1234.apps.googleusercontent.com",
                  "client_type": 3
                }
              ],
              "api_key": [
                {
                  "current_key": "AIzaSyDemoKey123456789"
                }
              ],
              "services": {
                "appinvite_service": {
                  "other_platform_oauth_client": [
                    {
                      "client_id": "123456789-abcd1234.apps.googleusercontent.com",
                      "client_type": 3
                    }
                  ]
                }
              }
            }
          ],
          "configuration_version": "1"
        }' > flutter_app/android/app/google-services.json

    - name: Get dependencies
      working-directory: flutter_app
      run: flutter pub get
      
    - name: Build APK (release)
      working-directory: flutter_app
      run: flutter build apk --release

    - name: Build AAB (release for Play)
      working-directory: flutter_app
      run: flutter build appbundle --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: IrtzaLink-APK
        path: flutter_app/build/app/outputs/flutter-apk/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: IrtzaLink-AAB
        path: flutter_app/build/app/outputs/bundle/release/app-release.aab

    - name: Create Release Notes
      run: |
        echo "## IrtzaLink Mobile App Release" > release_notes.md
        echo "" >> release_notes.md
        echo "### Features:" >> release_notes.md
        echo "- 📱 Complete profile management" >> release_notes.md
        echo "- 🔗 Social media links management" >> release_notes.md
        echo "- 📊 Analytics and statistics" >> release_notes.md
        echo "- 📱 QR code generation and scanning" >> release_notes.md
        echo "- 🎨 Professional UI/UX" >> release_notes.md
        echo "- 🔄 Real-time sync with Firebase" >> release_notes.md
