name: Build Flutter APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Install Android SDK 35
      shell: bash
      run: |
        yes | sdkmanager --licenses > /dev/null || true
        yes | sdkmanager "platforms;android-35" "build-tools;35.0.0" > /dev/null
        
    - name: Get dependencies
      working-directory: flutter_app
      run: flutter pub get
      
    - name: Build APK
      working-directory: flutter_app
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: IrtzaLink-APK
        path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
