name: Flutter CI

on:
  push:
    branches: [ main, master, feature/mobile-ui-3d-firebase-supabase ]
    paths:
      - 'flutter_app/**'
      - '.github/workflows/flutter_ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'flutter_app/**'
      - '.github/workflows/flutter_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        cache: true

    - name: Get Flutter version
      run: flutter --version
      
    - name: Change to Flutter directory
      run: cd flutter_app

    - name: Get dependencies
      run: cd flutter_app && flutter pub get

    - name: Verify dependencies
      run: cd flutter_app && flutter pub deps

    - name: Analyze project source
      run: cd flutter_app && flutter analyze --no-fatal-infos

    - name: Check formatting
      run: cd flutter_app && dart format --set-exit-if-changed .

    - name: Run tests
      run: cd flutter_app && flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: flutter_app/coverage/lcov.info
        flags: flutter
        name: flutter-coverage

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: cd flutter_app && flutter pub get

    - name: Generate code
      run: cd flutter_app && flutter packages pub run build_runner build --delete-conflicting-outputs

    - name: Build APK
      run: cd flutter_app && flutter build apk --release --no-shrink

    - name: Build iOS (dry run)
      run: cd flutter_app && flutter build ios --release --no-codesign --dry-run

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 7

  integration-test:
    runs-on: macos-latest
    if: github.event_name == 'push'
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: cd flutter_app && flutter pub get

    - name: Setup iOS Simulator
      run: |
        xcrun simctl list devices available
        xcrun simctl create test-device com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-0
        xcrun simctl boot test-device

    - name: Run integration tests
      run: |
        cd flutter_app
        flutter drive \
          --driver=test_driver/integration_test.dart \
          --target=integration_test/app_flow_test.dart \
          --device-id=test-device \
          --no-headless

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test-results
        path: flutter_app/integration_test/
        retention-days: 3